title: CE 40-817 Advanced Network Security
description: Sharif University · Course hub

theme: just-the-docs

url: "https://ce-40817.github.io"
baseurl: ""

color_scheme: brand
just_the_docs:
  search_enabled: true
  nav_external_links:
    - title: GitHub Org
      url: https://github.com/CE-40817